-- CreateTable
CREATE TABLE "Jabatan" (
    "KD_JABATAN" SERIAL NOT NULL,
    "JABATAN" TEXT NOT NULL,

    PRIMARY KEY ("KD_JABATAN")
);

-- CreateTable
CREATE TABLE "Status" (
    "KD_STATUS" SERIAL NOT NULL,
    "STATUS" TEXT NOT NULL,

    PRIMARY KEY ("KD_STATUS")
);

-- CreateTable
CREATE TABLE "Karyawan" (
    "id" SERIAL NOT NULL,
    "NAMA" TEXT NOT NULL,
    "ALAMAT" TEXT NOT NULL,
    "JABATAN_ID" INTEGER NOT NULL,
    "STATUS_ID" INTEGER NOT NULL,
    "ABSENSI_ID" INTEGER NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Absensi" (
    "NIP" SERIAL NOT NULL,
    "TGL_ABSEN" TEXT NOT NULL,
    "JAM_MASUK" TEXT NOT NULL,
    "JAM_KELUAR" TEXT NOT NULL,

    PRIMARY KEY ("NIP")
);

-- AddForeignKey
ALTER TABLE "Karyawan" ADD FOREIGN KEY ("JABATAN_ID") REFERENCES "Jabatan"("KD_JABATAN") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Karyawan" ADD FOREIGN KEY ("STATUS_ID") REFERENCES "Status"("KD_STATUS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Karyawan" ADD FOREIGN KEY ("ABSENSI_ID") REFERENCES "Absensi"("NIP") ON DELETE CASCADE ON UPDATE CASCADE;
